name: Laravel Workflow
on: push

jobs:
  build:
    name: Laravel build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel