name: Laravel Workflow
on: push

jobs:
  build:
    name: Laravel build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpcs
      - name: testando ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: 'cd /var/www/html/testando && sed -i -e "s/\r$//" .././server_deploy.sh'