name: Laravel Workflow
on: push

jobs:
  build:
    name: Laravel build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpcs
      - name: testando ssh
        uses: appleboy/ssh-action@master
        with:
          host: 51.222.32.199
          username: root
          password: huahua14
          port: 22
          script: whoami